// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/expense-groups/index.tsx";
import * as $4 from "./routes/expense-groups/new.tsx";
import * as $5 from "./routes/frivillig-tur.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/old.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/DenoEditor.tsx";
import * as $$2 from "./islands/ExpenseList.tsx";
import * as $$3 from "./islands/ExpenseNewForm.tsx";
import * as $$4 from "./islands/FileList.tsx";
import * as $$5 from "./islands/RefundForm.tsx";
import * as $$6 from "./islands/SignatureCanvas.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/expense-groups/index.tsx": $3,
    "./routes/expense-groups/new.tsx": $4,
    "./routes/frivillig-tur.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/old.tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/DenoEditor.tsx": $$1,
    "./islands/ExpenseList.tsx": $$2,
    "./islands/ExpenseNewForm.tsx": $$3,
    "./islands/FileList.tsx": $$4,
    "./islands/RefundForm.tsx": $$5,
    "./islands/SignatureCanvas.tsx": $$6,
  },
  baseUrl: import.meta.url,
};

export default manifest;
